apiVersion: v1
kind: Service
metadata:
  labels:
    app: newrelic-demo
  name: newrelic-demo
  namespace: demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: newrelic-demo